---
- name: copy module configuration
  copy:
    dest: /etc/modules-load.d/kubernetes-cri.conf
    src: kubernetes-cri.conf
  notify: load modules
- name: copy kernel configuration
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    src: 99-kubernetes-cri.conf
  notify: load kernel-params
- meta: flush_handlers
- name: enable apt repositories using HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
- name: add apt-key for Containerd
  apt_key:
    id: 8D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
- name: add apt-repository for Containerd
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
- name: install Containerd
  apt:
    name: containerd.io
    update_cache: yes
  notify: restart containerd
- name: make Containerd configuration file
  shell: mkdir -p /etc/containerd && containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
    warn: false
  notify: restart containerd
- name: edit Containerd configuration file
  lineinfile:
    backrefs: yes
    line: '\1 true'
    path: /etc/containerd/config.toml
    regexp: '^(\s*systemd_cgroup\s*=)'
  notify: restart containerd
- meta: flush_handlers
