---
- name: unhold Docker updates
  dpkg_selections:
    name: "{{ item }}"
    selection: deinstall
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli
- name: uninstall Docker
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: absent
- name: uninstall Docker daemon configuration
  file:
    path: /etc/docker/daemon.json
    state: absent
- name: remove Docker directory
  file:
    path: /var/lib/docker
    state: absent
  when: delete_local_data
