---
- name: unhold docker updates
  dpkg_selections:
    name: "{{ item }}"
    selection: deinstall
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli
- name: uninstall docker
  apt:
    force_apt_get: yes
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: absent
