---
- name: unhold docker updates
  dpkg_selections:
    name: "{{ item.split('=')[0] }}"
    selection: deinstall
  with_items: "{{ docker.apt.name }}"
- name: uninstall docker
  apt:
    force_apt_get: yes
    name: "{{ docker.apt.name }}"
    state: absent
