---
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-down
- hosts: k3s_worker
  roles:
    - k3s-worker-down
- hosts: k3s_master
  roles:
    - k3s-master-down
- hosts: all
  roles:
    - docker-down
- hosts: raspbian
  roles:
    - raspbian-swap-up
- hosts: ubuntu
  roles:
    - ubuntu-swap-up
- hosts:
    - raspbian
    - ubuntu
  roles:
    - debian-down
