---
- name: set video memory to 16mb
  lineinfile:
    line: "gpu_mem=16"
    path: /boot/firmware/config.txt
    regexp: '^\s*gpu_mem\s*=\s*'
  notify: reboot system
- name: program usb boot mode
  lineinfile:
    line: "program_usb_boot_mode=1"
    path: /boot/firmware/config.txt
    regexp: '^\s*program_usb_boot_mode\s*=\s*'
  notify: reboot system
- name: fix overscanning
  lineinfile:
    line: "#disable_overscan=1"
    path: /boot/firmware/config.txt
    regexp: '^\s*#?\s*disable_overscan\s*=\s*'
  notify: reboot system
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: update avahi-daemon
- name: edit /etc/hosts
  lineinfile:
    line: "{{ ansible_default_ipv4.address }}\t{{ inventory_hostname }}"
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}\s+'
- name: update and upgrade all existing packages
  apt:
    force_apt_get: yes
    only_upgrade: yes
    update_cache: yes
    upgrade: yes
  notify: reboot system
- name: enable Bonjour discovery
  apt:
    force_apt_get: yes
    name: avahi-daemon
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
- meta: flush_handlers
