---
# https://jamesachambers.com/raspberry-pi-ubuntu-server-18-04-2-installation-guide :
- name: set /boot/firmware/cmdline.txt
  copy:
    content: "dwc_otg.fiq_fix_enable=2 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait rootflags=noload net.ifnames=0\n"
    dest: /boot/firmware/cmdline.txt
  notify: reboot system
- name: set video memory to 16mb
  lineinfile:
    line: "gpu_mem = 16"
    path: /boot/firmware/config.txt
    regexp: '^\s*gpu_mem\s*=\s*'
  notify: reboot system
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: update avahi-daemon
- name: edit /etc/hosts
  lineinfile:
    line: "127.0.1.1\t{{ inventory_hostname }}"
    path: /etc/hosts
    regexp: '^127.0.1.1\t'
- name: update and upgrade all existing packages
  apt:
    force_apt_get: yes
    only_upgrade: yes
    update_cache: yes
    upgrade: yes
  notify: reboot system
- name: enable Bonjour discovery
  apt:
    force_apt_get: yes
    name: avahi-daemon
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
- meta: flush_handlers
