---
- name: add apt-key for k8s
  apt_key:
    id: 6A030B21BA07F4FB
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: add apt-repository for k8s
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  notify: apt-get update
- meta: flush_handlers
- name: install k8s
  apt:
    name:
      - "kubeadm={{ k8s_version }}"
      - "kubectl={{ k8s_version }}"
      - "kubelet={{ k8s_version }}"
    update_cache: yes
- name: hold k8s updates
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubectl
    - kubelet
