---
- name: set gpu_mem
  lineinfile:
    insertafter: '^\s*\[\s*all\s*\]'
    line: "gpu_mem=16"
    path: '{{ boot_directory }}/config.txt'
    regexp: '^\s*#?\s*gpu_mem\s*='
  notify: reboot system
- name: unset disable_oversan
  lineinfile:
    insertafter: '^\s*\[\s*all\s*\]'
    line: "#disable_overscan=1"
    path: '{{ boot_directory }}/config.txt'
    regexp: '^\s*#?\s*disable_overscan\s*='
  notify: reboot system
- name: set arm_64bit
  lineinfile:
    insertafter: '^\s*\[\s*all\s*\]'
    line: "arm_64bit={{ arm_64bit }}"
    path: '{{ boot_directory }}/config.txt'
    regexp: '^\s*#?\s*arm_64bit\s*='
  notify: reboot system
  when: arm_64bit != None
- name: set arm_freq
  lineinfile:
    insertafter: '^\s*\[\s*all\s*\]'
    line: "arm_freq={{ arm_freq }}"
    path: '{{ boot_directory }}/config.txt'
    regexp: '^\s*#?\s*arm_freq\s*='
  notify: reboot system
  when: arm_freq != None
- name: set over_voltage
  lineinfile:
    insertafter: '^\s*\[\s*all\s*\]'
    line: "over_voltage={{ over_voltage }}"
    path: '{{ boot_directory }}/config.txt'
    regexp: '^\s*#?\s*over_voltage\s*='
  notify: reboot system
  when: over_voltage != None
- name: remove macOS artifacts from /boot directory
  file:
    path: '{{ boot_directory }}/.Spotlight-V100'
    state: absent
- meta: flush_handlers
