---
- name: stat kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
- name: apply pre-master-down hooks
  changed_when: "'created' in pre_master_down.stdout or 'configured' in pre_master_down.stdout"
  local_action:
    module: 'command kubectl --kubeconfig=build/k8s-config.yaml apply --filename=hooks/{{ item }}.yaml'
    removes: 'hooks/{{ item }}.yaml' # it doesn't, but it prevents this step from running if it is
  register: pre_master_down
  run_once: yes
  vars:
    ansible_become: no
  with_items:
    - pre-master-down
    - k8s-pre-master-down
  when: kubelet_conf.stat.exists
- name: drain and delete node
  failed_when: false
  local_action:
    module: shell
    _raw_params: |
      export KUBECONFIG=build/k8s-config.yaml
      kubectl drain {{ inventory_hostname }} --delete-local-data={% if delete_local_data %}true{% else %}false{% endif %} --force --ignore-daemonsets
      kubectl delete node {{ inventory_hostname }}
    removes: build/k8s-config.yaml # it doesn't, but it prevents this step from running if it is
  vars:
    ansible_become: no
  when: kubelet_conf.stat.exists
- name: kubeadm reset
  command: kubeadm reset --force
  when: kubelet_conf.stat.exists
  notify: clean iptables
- name: unhold k8s updates
  dpkg_selections:
    name: "{{ item }}"
    selection: deinstall
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - kubernetes-cni
- name: uninstall k8s
  apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
    state: absent
- meta: flush_handlers
