---
- name: enable apt repositories using HTTPS
  apt:
    force_apt_get: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
- name: add apt-key for docker
  apt_key:
    id: "{{ docker.apt_key.id }}"
    url: "{{ docker.apt_key.url }}"
- name: add apt-repository for docker
  apt_repository:
    repo: "{{ docker.apt_repository.repo }}"
- name: install docker
  apt:
    force_apt_get: yes
    name:
      - containerd.io
      - "{{ docker.apt.name }}"
    update_cache: yes
  notify: restart docker
- name: hold docker updates
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - containerd.io
    - docker-ce
- name: write docker daemon configuration
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
  notify: restart docker
- name: make docker service configuration directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify: restart docker
- meta: flush_handlers
