---
- name: enable apt repositories using HTTPS
  apt:
    force_apt_get: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
- name: add apt-key for docker
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"
- name: add apt-repository for docker
  apt_repository:
    repo: "{{ docker_apt_repository }}"
- name: install docker
  apt:
    force_apt_get: yes
    name:
      - "containerd.io={{ containerd_version }}"
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
- name: hold docker updates
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli
- name: install docker daemon configuration
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.jinja
  notify: restart docker
- meta: flush_handlers
