---
- name: enable apt repositories using HTTPS
  apt:
    force_apt_get: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
- name: add apt-key for docker
  apt_key:
    id: "{{ docker.apt_key.id }}"
    url: "{{ docker.apt_key.url }}"
- name: add apt-repository for docker
  apt_repository:
    repo: "{{ docker.apt_repository.repo }}"
- name: install docker
  apt:
    force_apt_get: yes
    name: "{{ docker.apt.name }}"
    update_cache: yes
- name: hold docker updates
  dpkg_selections:
    name: "{{ item.split('=')[0] }}"
    selection: hold
  with_items: "{{ docker.apt.name }}"
