---
- name: enable apt repositories using HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
- name: add apt-key for Docker
  apt_key:
    id: 8D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
- name: add apt-repository for Docker CE
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
- name: install Docker
  apt:
    name:
      - "docker-ce=5:18.09.8~3-0~ubuntu-{{ansible_lsb.codename}}"
    update_cache: yes
  notify: restart docker
- name: copy Docker configuration
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
  notify: restart docker
- name: make Docker configuration directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify: restart docker
- meta: flush_handlers
