---
- name: set /boot/cmdline.txt
  copy:
    content: "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\n"
    dest: /boot/cmdline.txt
  notify: reboot system
- name: set /boot/config.txt
  copy:
    src: config.txt
    dest: /boot/config.txt
  notify: reboot system
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: update avahi-daemon
- name: edit /etc/hosts
  lineinfile:
    line: "127.0.1.1\t{{ inventory_hostname }}"
    path: /etc/hosts
    regexp: '^127.0.1.1\t'
- name: remove MacOS artifacts from /boot directory
  file:
    path: /boot/.Spotlight-V100
    state: absent
- name: update and upgrade all existing packages
  apt:
    only_upgrade: yes
    update_cache: yes
    upgrade: yes
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
- meta: flush_handlers
