---
# tasks file for ubuntu-server-raspi4
# https://jamesachambers.com/raspberry-pi-ubuntu-server-18-04-2-installation-guide
- name: disable firmware updates
  apt:
    name:
      - flash-kernel
      - initramfs-tools
    state: absent
  notify: reboot system
- name: remove obsolete or unused packages
  apt:
    autoclean: yes
    autoremove: yes
  notify: reboot system
- meta: flush_handlers
- name: update and upgrade all existing packages
  apt:
    only_upgrade: yes
    update_cache: yes
    upgrade: yes
  notify: reboot system
- name: enable Bonjour discovery
  apt:
    name: avahi-daemon
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  notify: update avahi-daemon
- meta: flush_handlers
