---
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies
  when: proxy_url != ''
- name: add environment variable NO_PROXY
  lineinfile:
    line: '{{ item }}=localhost,127.0.0.0/8,*.local'
    path: /etc/environment
    regexp: '^\s*{{ item }}\s*=\s*'
  notify: reboot system
  when: proxy_url != ''
  with_items:
    - no_proxy
    - NO_PROXY
- name: add environment variables HTTP_PROXY and HTTPS_PROXY
  lineinfile:
    line: '{{ item }}={{ proxy_url }}'
    path: /etc/environment
    regexp: '^\s*{{ item }}\s*=\s*'
  notify: reboot system
  when: proxy_url != ''
  with_items:
    - http_proxy
    - HTTP_PROXY
    - https_proxy
    - HTTPS_PROXY
- meta: flush_handlers
